### ISSUE TITLE
Не выполняется SQL-скрипт

### ISSUE THREAD

**Issue by vmulyukin** [vl0ft/guestbook#1]
Выполняю скрипт из файла guestbook/src/main/resources/sql/Create_guestbook_db_and_user_comments_table.sql 
выходит ошибка:

> ERROR:  CREATE DATABASE cannot be executed from a function or multi-command string
> ********** Ошибка **********
> 
> ERROR: CREATE DATABASE cannot be executed from a function or multi-command string
> SQL-состояние: 25001

Клиент PgAdmin 1.22.2

**Comment by vial0ft** [comment]
Полагаю, что после модификации процесса создания базы данных через [шелл-скрипт](https://github.com/vl0ft/guestbook/blob/master/src/main/resources/scripts/init_db.sh) проблема не будет актуальна?

**Comment by vmulyukin** [comment]
Да, разделение скриптов и изменение инструкции решает эту проблему.
