### ISSUE TITLE
БД guestbook пуста после прогона SQL-скрипта

### ISSUE THREAD

**Issue by vmulyukin** [vl0ft/guestbook#2]
Выполнил скрипт guestbook/src/main/resources/sql/Create_guestbook_db_and_user_comments_table.sql - каждый statement отдельно: БД guestbook появилась, но она пуста, таблица user_comments в схеме public не появилась.

**Comment by vial0ft** [comment]
Почему-то наивно надеялся, что таблицу он создаст с новоиспечённой базе. Увы.
Модифицировал процесс создания базы и таблицы - через [init_db.sh](https://github.com/vl0ft/guestbook/blob/master/src/main/resources/scripts/init_db.sh) скрипт.
