### ISSUE TITLE
Не очищается поле комментария после ввода

### ISSUE THREAD

**Issue by vmulyukin** [vl0ft/guestbook#3]
Ввожу имя пользователя и комментарий, нажимаю на кнопку `add`. 
Имя пользователя и комментарий появляются в левой части, но поле комментария и поле имени пользователя не очищаются. Поле комментария заполняется какими-то кодами:
![guestbook1](https://cloud.githubusercontent.com/assets/25965099/23235233/93ebc3b4-f976-11e6-9b32-8d8452ac26c4.png)

**Comment by vial0ft** [comment]
При добавлении комментария, в [CommentController.java](https://github.com/vl0ft/guestbook/blob/master/src/main/java/com/loki/work/CommentController.java) в молель не передавался объект нового комметария в случае, если ошибок валидации не было.
Исправил.
Так же исправил проблему с кодировкой - в [web.xml](https://github.com/vl0ft/guestbook/blob/master/src/main/webapp/WEB-INF/web.xml) не был добавлен фильтер для приведения к utf-8.
